import Head from "next/head";
import { Avatar, Flex, Text } from "@chakra-ui/react";
import { Eye, Sun, EyeOff } from "react-feather";
import FinancialHealth from "@/components/FinancialHealth";
import OurBalance from "@/components/OurBalance";
import CreditCard from "@/components/CreditCard";
import { useAuth } from "@/Contexts/AuthProvider";
import { useRouter } from "next/router";
import { useExpensesContext } from "@/Contexts/ExpensesProvider";
import { useState } from "react";
import Rewards from "@/components/Rewards";
import HeadLogo from "@/components/HeadLogo";
import Benefits from "@/components/Benefits";
import Caixinhas from "@/components/Caixinhas";

export default function Home() {
  const { user } = useAuth();
  const { getFinanceHealth, getSaldo, getIncome, getOutcome } =
    useExpensesContext();
  const { push } = useRouter();

  const [hideSaldo, setHideSaldo] = useState(false);

  if (!user) {
    push("/login");
  }
  return (
    <>
      <Head>
        <title>Caixa Teens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        className="header-cotaniner"
        p="24px 16px"
        bgColor={"#000"}
        w="100%"
        fontFamily={"Lexend"}
      >
        <Flex className="header-content" flexDir="column" w="100%" gap={"24px"}>
          <Flex className="logo-area">
            <HeadLogo />
          </Flex>

          <Flex
            className="profile-area"
            color="#fff"
            justifyContent={"space-between"}
            alignItems={"center"}
          >
            <Flex gap="16px">
              <Avatar
                borderRadius={"10px"}
                src="https://br.web.img2.acsta.net/pictures/16/05/17/17/28/208580.jpg"
              />

              <Flex flexDir={"column"} w="80%">
                <Text fontSize={"16px"} fontWeight={"bold"}>
                  {user?.name}
                </Text>
                <Flex
                  fontSize={"12px"}
                  flexDir="row"
                  w="100%"
                  gap={"4px"}
                  alignItems={"center"}
                  color={"#FBFCFE"}
                >
                  <Text>Bom dia</Text>
                  <Sun size={"16px"} />
                </Flex>
              </Flex>
            </Flex>

            <Flex
              padding={"8px"}
              background={"rgba(255, 255, 255, 0.10)"}
              align={"center"}
              justify={"center"}
              h="40px"
              w="40px"
              borderRadius={"5px"}
              cursor="pointer"
              onClick={() => setHideSaldo((state) => !state)}
            >
              {hideSaldo ? <EyeOff size="24px" /> : <Eye size="24px" />}
            </Flex>
          </Flex>

          <Flex className="balance" color={"#fff"} flexDir={"column"}>
            <Text fontSize="14px" lineHeight="22px">
              Seu Saldo
            </Text>
            <Flex gap={"2px"}>
              <Text
                className="balance-area"
                fontSize={"28px"}
                lineHeight="36px"
                fontWeight={"bold"}
              >
                R$
              </Text>
              <Text fontSize={"28px"} lineHeight="36px" fontWeight={"bold"}>
                {hideSaldo ? "******" : getSaldo()}
              </Text>
            </Flex>
          </Flex>
        </Flex>
      </Flex>
      <Flex bgColor={"#000"} flexDir={"column"} gap={"20px"} p="0 16px">
        <OurBalance
          hideSaldo={hideSaldo}
          income={getIncome()}
          outcome={getOutcome()}
          bank={876}
        />

        <CreditCard />

        <FinancialHealth
          onClick={() => push("/expenses")}
          value={getFinanceHealth()}
        />

        <Rewards />
        <Caixinhas />
        <Benefits />
      </Flex>
    </>
  );
}
