import Head from 'next/head'
import MenuButton from '@/components/MenuButton'

export default function Home() {
  return (
    <>
      <Head>
        <title>Caixa Teens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MenuButton icon={<></>} title="Ola" />
      </main>
    </>
  )
}
