import Head from 'next/head'
import MenuButton from '@/components/MenuButton'
import { EmailIcon } from '@chakra-ui/icons'
import HeadLogo from '@/components/HeadLogo'
import HealthCard from '@/components/HealthCard'

export default function Home() {
  return (
    <>
      <Head>
        <title>Caixa Teens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeadLogo />

        <HealthCard healthValue={23} />

        <MenuButton icon={<EmailIcon color="var(--white)" />} title="Ola" />
      </main>
    </>
  )
}
